---
#title: "Capstone Project Proposal"
#author: "Gabriel Fontenot"
#date: "3/09/2018"
output: html_document
---

## Capstone Project Proposal
###### *Introduction to Data Science by Springboard*
### Network Data Flow analysis
##### By Gabriel Fontenot
***

### Introduction
Network infrastructure is the foundation for applications that define businesses as we know them today. As the user community becomes more data driven with business, social and gaming applications, the need for streamlining operation and for identifying trends and anomalies become top of mind.

### The Problem
Being part of the network engineering community, we have been collecting data for decades. A common challenge (or maybe better stated as an opportunity) is to be able to leverage the collected data to infer data points from the overall content that can assist in making better operational and usage decisions. To be successful, we need to better understand data points that can be gleaned from the content to help understand day to day operations. What can then apply learning to help make our applications better fit for the ever-growing community of users.  

### The Client
The main users for this analysis are:

* Network Architects: Better understand application usage and behavior to assist in corresponding network design

* Network Engineers: Provide a meaningful benchmark to application behavior

* Network Operations: Benchmark application behavior across time periods to understand changes

* Business Owners: Understand how application design can affect performance and usage


### The Data
The data set for this project is comprised of two inputs, a representation of the network traffic between a set of hosts for a period of time and a representation of the host to describe their overall functionality. Merged into a single data set, the overall data contains 14k records and 14 columns.


### The Approach
The following steps highlight the strategy to be adopted for carrying out the analysis for the Capstone project:

1. Data Wrangling and Cleaning
	+ Deal with missing values: Use domain information to determine if missing values should be discarded
	+ Dropping columns that are irrelevant to the analysis
	+ Rearrange and transform dataset for cleaner analysis.
2. Exploratory Data Analysis
	+ Perform Regression Analysis to determine factors that most influence the outcome of loan origination
	+ Identify patterns and correlation between the different variables
	+ Use data visualization for graphical analysis to answer questions on the dataset
3. Predictive Analysis
	+ Apply machine learning techniques to see if the outcome of a home loan origination (i.e. loan approved or denied) can be predicted based on borrower and lender characteristics


### The Deliverables
The deliverables for this project will include a report of all the findings, a slide deck and R code, all of which will be published on GitHub.


### Specific questions to be explored
1.	The total number of source and destination pairs part of the flows
2.  The number of provided services for each host / based on host type
3.  The volume of flows to each host based on services provided
4.  The volume of flows from each host based on services consumed
5.  The overall distribution of traffic across services provided
6.  Does the host type contribute to the overall flow behavior
7.  What anomalies or outliers are present within the data
8.  Understand the protocol distribution over the specified time interval
9.  How are packet sizes in flow analysis distributed across host operating systems
10. Does host OS distribution affect packet flow
11. Does host OS distribution affect services provided
12. Understand host grouping/distribution for services provided

